identifier_name:
  excluded:
    - db
    - id
    - URL
  allowed_symbols: ["_"]

type_name:
  allowed_symbols: ["_"]

opt_in_rules:
  - convenience_type
  - empty_count
  - empty_string
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters_brackets
  - non_overridable_class_declaration
  - number_separator
  - operator_usage_whitespace
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - private_swiftui_state
  - redundant_nil_coalescing
  - redundant_self_in_closure
  - redundant_type_annotation
  - shorthand_optional_binding
  - strict_fileprivate
  - superfluous_else
  - toggle_bool
  - trailing_closure
  - unhandled_throwing_task
  - unneeded_parentheses_in_closure_argument
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate

analyzer_rules:
  - unused_import

disabled_rules:
  - trailing_comma
  - vertical_whitespace_opening_braces
  - comment_spacing

line_length: 130

indentation_width:
  indentation_width: 2
  include_comments: false
  include_multiline_strings: false
    
