name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Select Xcode 15.4
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    - name: Build, test, code coverage
      run: make
    - name: Create Coverage Badge
      uses: schneegans/dynamic-badges-action@v1.1.0
      with:
        auth: ${{ secrets.GIST_UPDATE }}
        gistID: 54c92d8df32d9a1b64d945f2e76696f1
        filename: SwiftDataTCA-coverage.json
        label: Coverage
        message: ${{ env.PERCENTAGE }}
        color: success
